# Generated by Django 3.1.6 on 2021-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
