# Generated by Django 3.1.6 on 2021-12-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_thumbail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
