# Generated by Django 3.1.6 on 2021-12-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211213_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thumbail',
            new_name='thumbnail',
        ),
    ]
